services:
  chain-server:
    container_name: chain-server-healthcare-assistant
    image: chain-server-healthcare-assistant:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: python3 chain_server/chain_server.py --assistant intake --port 8081
    ports:
    - "8081:8081"
    expose:
    - "8081"
    volumes:
      - ./graph_definitions/graph_images:/graph_images
      - ./graph_definitions:/app/graph_definitions
      - ./nmgr-config-store:/app/nmgr-config-store
      - ./vars.env:/env_vars/vars.env
      - ./chain_server:/app/chain_server
    shm_size: 5gb
    


  patient-intake-ui:
    container_name: patient-intake-ui
    image: patient-intake-ui:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: python3 graph_definitions/graph_patient_intake_only.py --port 7860
    ports:
    - "7860:7860"
    expose:
    - "7860"
    volumes:
      - ./graph_definitions/graph_images:/graph_images
      - ./graph_definitions:/app/graph_definitions
      - ./nmgr-config-store:/app/nmgr-config-store
      - ./vars.env:/env_vars/vars.env
    shm_size: 5gb
    



  appointment-making-ui:
    container_name: appointment-making-ui
    image: appointment-making-ui:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 graph_definitions/graph_appointment_making_only.py --port 7860
    environment:
      - WATCHFILES_FORCE_POLLING=true
    ports:
    - "7860:7860"
    expose:
    - "7860"
    volumes:
      - ./graph_definitions/graph_images:/graph_images
      - ./graph_definitions:/app/graph_definitions
      - ./nmgr-config-store:/app/nmgr-config-store
      - ./vars.env:/env_vars/vars.env
    shm_size: 5gb
    

  medication-lookup-ui:
    container_name: medication-lookup-ui
    image: medication-lookup-ui:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 graph_definitions/graph_medication_lookup_only.py --port 7860
    environment:
      - WATCHFILES_FORCE_POLLING=true
    ports:
    - "7860:7860"
    expose:
    - "7860"
    volumes:
      - ./graph_definitions/graph_images:/graph_images
      - ./graph_definitions:/app/graph_definitions
      - ./nmgr-config-store:/app/nmgr-config-store
      - ./vars.env:/env_vars/vars.env
    shm_size: 5gb
  

  full-agent-ui:
    container_name: full-agent-ui
    image: full-agent-ui:${TAG:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 graph_definitions/graph.py --port 7860
    environment:
      - WATCHFILES_FORCE_POLLING=true
    ports:
    - "7860:7860"
    expose:
    - "7860"
    volumes:
      - ./graph_definitions/graph_images:/graph_images
      - ./graph_definitions:/app/graph_definitions
      - ./nmgr-config-store:/app/nmgr-config-store
      - ./vars.env:/env_vars/vars.env
    shm_size: 5gb
    