models:
  - type: main
    engine: nvidia_ai_endpoints
    model: meta/llama-3.1-70b-instruct
    #model_id: meta/llama-3.1-8b-instruct
    base_url: https://integrate.api.nvidia.com/v1
    

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output